package frc.robot;

import com.ctre.phoenix6.configs.TalonFXConfiguration;

/**
 * Global constants for all subsystems.
 *
 * This file coexists with TunerConstants (auto-generated by CTRE)
 * and should not be placed in the "generated" package.
 *
 * Each subsystem gets its own inner class for clarity and organization.
 */
public final class Constants {

    // ==========================================================
    // Arm Subsystem Constants (Hippo Arm Project)
    // ==========================================================
    public static final class Arm {
        /** CAN IDs for hardware devices */
        public static final int ARM_MOTOR_ID = 13; // Kraken X60 (TalonFX)
        public static final int ARM_ENCODER_ID = 14; // Through-bore CANcoder on arm pivot

        /** Inversions — adjust based on wiring or desired movement direction */
        public static final boolean ARM_MOTOR_INVERTED = false; // Flip to true if arm moves wrong way
        public static final boolean ARM_ENCODER_INVERTED = false; // Flip if CANcoder angle increases in opposite
                                                                  // direction

        /** Gear ratio (motor : arm) — 4:1 MaxPlanetary × 3:1 chain = 12:1 */
        public static final double ARM_GEAR_RATIO = 12.0;

        /**
         * CANcoder offset — measure the CANcoder’s absolute position when the arm is
         * perfectly horizontal
         */
        public static final double ARM_CANCODER_ABS_OFFSET = 0.312; // Example value; set yours via Phoenix Tuner X

        // ----------------------------------------------------------
        // PID tuning gains for CANcoder-based position control
        // ----------------------------------------------------------
        public static final double ARM_kP = 3.0;
        public static final double ARM_kI = 0.0;
        public static final double ARM_kD = 0.1;

        // ----------------------------------------------------------
        // Motion control and safety configuration
        // ----------------------------------------------------------
        public static final double ARM_MAX_PERCENT_OUTPUT = 0.5; // Limits motor output for safe testing
        public static final double JOYSTICK_DEADBAND = 0.08; // Ignores small joystick input noise

        /** Optional rotation soft limits (in arm shaft rotations) */
        public static final double ARM_MIN_ROT = -0.75; // ~ -270°
        public static final double ARM_MAX_ROT = 0.75; // ~ +270°

        /** TalonFX configuration object — preloaded with PID and soft limits */
        public static final TalonFXConfiguration armConfig = new TalonFXConfiguration();

        static {
            // PID defaults (for older configurations or tuning references)
            armConfig.Slot0.kP = 2.0;
            armConfig.Slot0.kI = 0.0;
            armConfig.Slot0.kD = 0.1;

            // Software limits — expressed in motor shaft rotations
            // Example: 0° arm = 0 rotations; 180° arm = 0.5 turns × 12:1 = 6 motor
            // rotations
            armConfig.SoftwareLimitSwitch.ReverseSoftLimitEnable = true;
            armConfig.SoftwareLimitSwitch.ReverseSoftLimitThreshold = 0.0;

            armConfig.SoftwareLimitSwitch.ForwardSoftLimitEnable = true;
            armConfig.SoftwareLimitSwitch.ForwardSoftLimitThreshold = 6.0;
        }
    }

    // ==========================================================
    // Add additional subsystem constants below as needed
    // Example: Drivebase, Elevator, Intake, etc.
    // ==========================================================
}
